# Postgres database
defaults: &defaults
  adapter: postgresql
  database: d3e0jdj04cnfs
  username: ardqxjrtttslij
  password: K2TCSJw7xuC2FTGAS6hZb2fGuO
  host: ec2-54-197-241-95.compute-1.amazonaws.com

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  <<: *defaults

cucumber:
  <<: *test